//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EntityExample.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PeopleModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PeopleModelContainer object using the connection string found in the 'PeopleModelContainer' section of the application configuration file.
        /// </summary>
        public PeopleModelContainer() : base("name=PeopleModelContainer", "PeopleModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PeopleModelContainer object.
        /// </summary>
        public PeopleModelContainer(string connectionString) : base(connectionString, "PeopleModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PeopleModelContainer object.
        /// </summary>
        public PeopleModelContainer(EntityConnection connection) : base(connection, "PeopleModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<People> PeopleSet
        {
            get
            {
                if ((_PeopleSet == null))
                {
                    _PeopleSet = base.CreateObjectSet<People>("PeopleSet");
                }
                return _PeopleSet;
            }
        }
        private ObjectSet<People> _PeopleSet;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PeopleSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPeopleSet(People people)
        {
            base.AddObject("PeopleSet", people);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PeopleModel", Name="People")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class People : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new People object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static People CreatePeople(global::System.Guid id)
        {
            People people = new People();
            people.Id = id;
            return people;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Familyname
        {
            get
            {
                return _Familyname;
            }
            set
            {
                OnFamilynameChanging(value);
                ReportPropertyChanging("Familyname");
                _Familyname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Familyname");
                OnFamilynameChanged();
            }
        }
        private global::System.String _Familyname;
        partial void OnFamilynameChanging(global::System.String value);
        partial void OnFamilynameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Firstname
        {
            get
            {
                return _Firstname;
            }
            set
            {
                OnFirstnameChanging(value);
                ReportPropertyChanging("Firstname");
                _Firstname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Firstname");
                OnFirstnameChanged();
            }
        }
        private global::System.String _Firstname;
        partial void OnFirstnameChanging(global::System.String value);
        partial void OnFirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Secondname
        {
            get
            {
                return _Secondname;
            }
            set
            {
                OnSecondnameChanging(value);
                ReportPropertyChanging("Secondname");
                _Secondname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Secondname");
                OnSecondnameChanged();
            }
        }
        private global::System.String _Secondname;
        partial void OnSecondnameChanging(global::System.String value);
        partial void OnSecondnameChanged();

        #endregion

    
    }

    #endregion

    
}
